<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Correctness</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>61d94835-386d-4dfb-b957-794b15a2438d</testSuiteGuid>
   <testCaseLink>
      <guid>c04dd899-eef0-425a-8854-a49a30f554e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_forminputname_correctness</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68eabbdd-9afd-4887-95e5-906d38f7fe6b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT Form Input Name Correctness</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>68eabbdd-9afd-4887-95e5-906d38f7fe6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>86ee55eb-cfbb-4aae-ac58-d99bd1d48188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68eabbdd-9afd-4887-95e5-906d38f7fe6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>testType</value>
         <variableId>c90c8dbd-5d8e-4b03-b092-14e0c7d48043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68eabbdd-9afd-4887-95e5-906d38f7fe6b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>b5ba1c43-7e7f-40b8-a426-87414b82df47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>496db8f8-c51e-40b1-9912-46d0776dd0cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_formselectgender_correctness</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>19050fce-c129-410b-a725-202f54f2c481</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_forminputage_correctness</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>317cba0d-f6e2-4262-bbdd-042f0694e6be</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT Form Input Age Correctness</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>317cba0d-f6e2-4262-bbdd-042f0694e6be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>age</value>
         <variableId>9024025b-9065-4606-be32-6ea130eaad23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>317cba0d-f6e2-4262-bbdd-042f0694e6be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>testType</value>
         <variableId>efdb38d1-aac1-4e04-ab0c-1da1a53d0f34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>317cba0d-f6e2-4262-bbdd-042f0694e6be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>0233091e-4d6d-4a72-9872-b29e4be40ba1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a828454-f16d-48b2-b212-24113b3dcdc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_formselectactivity_correctness</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8ac72112-a4e8-4c43-952c-4a040fce7402</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_generatequotes_correctness</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>87382d28-b2c9-4e6c-ba16-934d4391edbc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT Generate Quotes Correctness</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>87382d28-b2c9-4e6c-ba16-934d4391edbc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>feeling</value>
         <variableId>4d309fac-6da2-44f5-ad9f-9c781787fe4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>87382d28-b2c9-4e6c-ba16-934d4391edbc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>testType</value>
         <variableId>4440eb6e-c7b6-4ab9-b17d-adeb3517bfe9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>87382d28-b2c9-4e6c-ba16-934d4391edbc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>ee9737c1-2d10-4bd7-95c7-4c70f96a13e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b967af29-19fc-4230-9a68-0b2493e3febc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_editname_correctness</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>37fcd596-f5b4-4c2b-9c36-7904de7e9c04</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT Edit Name Correctness</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>37fcd596-f5b4-4c2b-9c36-7904de7e9c04</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>c416b84d-5690-421a-ab6e-0d7bef809325</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>37fcd596-f5b4-4c2b-9c36-7904de7e9c04</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>testType</value>
         <variableId>3f3f1742-8619-4968-9e48-442a783024e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>37fcd596-f5b4-4c2b-9c36-7904de7e9c04</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>bab2af01-3b08-4455-8a9a-5cb54e64ebc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b6269d2-0f35-45d8-9df1-0db9c3cfc7ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_editgender_correctness</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6d7b965a-6a9d-424b-90ed-14a1e5463652</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_editage_correctness</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d643b289-d38b-4460-8ac3-695ff06c0ed8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DDT Edit Age Correctness</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d643b289-d38b-4460-8ac3-695ff06c0ed8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>age</value>
         <variableId>6aa495e6-3cdf-4d33-b4b1-8bcba6595c7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d643b289-d38b-4460-8ac3-695ff06c0ed8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>testType</value>
         <variableId>3813fe56-c9e2-44c4-af9f-1779fbc48564</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d643b289-d38b-4460-8ac3-695ff06c0ed8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedResult</value>
         <variableId>da7f5406-6203-4e1b-b8fb-6a832c772657</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1b5cc05-0d82-4aeb-8ac0-ab2314130e52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tc_editactivity_correctness</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
